export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary": "#e6c364",
        "primary-container": "#c9a84c",
        "secondary": "#e0c56e",
        "secondary-container": "#645100",
        "tertiary": "#e4c46a",
        "background": "#16130d",
        "surface": "#16130d",
        "surface-container": "#221f19",
        "surface-container-low": "#1e1b15",
        "surface-container-high": "#2d2a23",
        "surface-container-highest": "#38342d",
        "surface-container-lowest": "#100e08",
        "surface-variant": "#38342d",
        "surface-bright": "#3d3931",
        "surface-dim": "#16130d",
        "on-primary": "#3d2e00",
        "on-secondary": "#3b2f00",
        "on-tertiary": "#3d2f00",
        "on-background": "#e9e1d7",
        "on-surface": "#e9e1d7",
        "on-surface-variant": "#d0c5b2",
        "outline": "#99907e",
        "outline-variant": "#4d4637",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "inverse-surface": "#e9e1d7",
        "inverse-on-surface": "#343029",
        "inverse-primary": "#755b00",
        "primary-fixed": "#ffe08f",
        "primary-fixed-dim": "#e6c364",
        "secondary-fixed": "#fde187",
        "secondary-fixed-dim": "#e0c56e",
        "tertiary-container": "#c7a952",
        "tertiary-fixed": "#ffe08b",
        "tertiary-fixed-dim": "#e3c36a",
        "on-primary-container": "#503d00",
        "on-secondary-container": "#dfc46e",
        "on-tertiary-container": "#4f3e00",
        "on-primary-fixed": "#241a00",
        "on-primary-fixed-variant": "#584400",
        "on-secondary-fixed": "#231b00",
        "on-secondary-fixed-variant": "#564500",
        "on-tertiary-fixed": "#241a00",
        "on-tertiary-fixed-variant": "#584400",
        "surface-tint": "#e6c364",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        "unit": "8px",
        "gutter": "24px",
        "container-max": "1440px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.7", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.7", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.7", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1440px",
      },
    },
  },
  plugins: [],
}
