export const USER_BY_EMAIL = 'USER_BY_EMAIL';
export const CLEAN_USER_BY_EMAIL = 'CLEAN_USER_BY_EMAIL';
export const USER_BY_NICK = 'USER_BY_NICK';
export const ADMINISTRAR_USER = 'ADMINISTRAR_USER';
export const PROMO1K = 'PROMO1K';
export const REMOVE_FAVORITE_SUCCESS = 'REMOVE_FAVORITE_SUCCESS';
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS';
export const VIEW_USER_PROFILE = 'VIEW_USER_PROFILE';
export const FETCH_FAVORITES_FAILURE = 'FETCH_FAVORITES_FAILURE';
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS';
export const FETCH_PUBLIC_FAVORITES = 'FETCH_PUBLIC_FAVORITES';
export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const USER_ACTION_ERROR = 'USER_ACTION_ERROR';
export const CREATE_GAME_REQUEST = 'CREATE_GAME_REQUEST';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_FAILURE = 'CREATE_GAME_FAILURE';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const CLEAR_AUTH_TOKEN = 'CLEAR_AUTH_TOKEN';

// Friends
export const FRIENDS_LIST_SUCCESS = 'FRIENDS_LIST_SUCCESS';
export const FRIENDS_INCOMING_SUCCESS = 'FRIENDS_INCOMING_SUCCESS';
export const FRIENDS_OUTGOING_SUCCESS = 'FRIENDS_OUTGOING_SUCCESS';
export const FRIENDS_RELATIONSHIP_SUCCESS = 'FRIENDS_RELATIONSHIP_SUCCESS';
export const FRIENDS_ACTION_ERROR = 'FRIENDS_ACTION_ERROR';

// Messages
export const MESSAGES_CONVERSATIONS_SUCCESS = 'MESSAGES_CONVERSATIONS_SUCCESS';
export const MESSAGES_THREAD_SUCCESS = 'MESSAGES_THREAD_SUCCESS';
export const MESSAGES_ACTION_ERROR = 'MESSAGES_ACTION_ERROR';

// Admin
export const ADMIN_OVERVIEW_SUCCESS = 'ADMIN_OVERVIEW_SUCCESS';
export const ADMIN_ACTION_ERROR = 'ADMIN_ACTION_ERROR';
